### ISSUE TITLE
Changing audio source during/after a call

### ISSUE THREAD

**Issue by cemevin** [plivo/plivo-websdk-2.0-example#1]
Hello,

I am programming a phone application using your sdk, utilizing different audio sources. I tried to work with version 1 sdk, but since it didn't allow me to change the audio source, I switched to version 2.

The example webpage you offered here works fine for changing the input source. However after I make a call, even if I change the input source, the changes aren't reflected in Chrome. I have to refresh the page, select the input source again, then make a call. 

I added this code to reflect the changes in Chrome, but although it changes the settings for Chrome, the changes didn't reflect on plivo:

`var selectDev = $('#micDev').val();`
`plivoWebSdk.client.audio.microphoneDevices.set(selectDev);`
`var mediaConstraints = {audio:{deviceId: selectDev ? {exact: selectDev} : true}, video:false};`
`navigator.mediaDevices.getUserMedia(mediaConstraints);`

Is there a way to change microphone/speakers after having made a call, without refreshing the page? Thank you.

Best,
Cem

**Comment by sasi-plivo** [comment]
HI @cemevin, You don't need to access `navigator.mediaDevices.getUserMedia(mediaConstraints)`;  
separately. If you pass plivoWebSdk.client.audio.microphoneDevices.set(deviceID), we'll be using the deviceID and access `getUserMedia` again before making the call.
1. You can set  `microphoneDevices.set(selectDev)` during ongoing call but it will get reflected only on next call If `permOnClick:true`.  Since the local `stream` is already using the default device, you can't change and reflect the Mic device source like you do for `ringtoneDevices` or `speakerDevices`
2. You can't change and reflect a new microphone device for an existing active stream. Only on new `getUserMedia()` instance you can reflect the new mic device. 
3. Technically updating new audio track for an existing local stream will require regeneration in SDP.

**Comment by sasi-plivo** [comment]
@cemevin , Do feel free to re-open this ticket if you still have issues
